### ISSUE TITLE
[meta] The crawler shouldn't know about IndicePA (ipa)

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-backend#292]
IndicePA is an Italian thing and the crawler shouldn't know it exists

- [x] Don't update `amministrazioni.it` and save its data codes into Elastic, move that component elsewhere (https://github.com/italia/developers.italia.it-data/pull/11)
- [x] Don't export `amministrazioni.yml` (#243)
- [x] Don't save `it-riuso-codiceIPA-label` into Elastic (#291)

**Comment by bfabio** [comment]
Fixed by #302.
